name: Keep Render Backend Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes (UTC)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render API to keep alive
        run: |
          curl -s https://fantasy-cricket-react.onrender.com/api/v1/players || echo "Ping failed"
